---
title: "Starwars Flex Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: sandstone
    favicon: favicon.png
---


<!-- CSS Style Modifications -->
<!-- Hide the Navbar Title -->
<style>
.navbar-brand {
  display: none;
}
</style>

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(reshape2)
library(dplyr)
library(plotly)

pdf(NULL)

starwars.load <- starwars %>%
  mutate(films = as.character(films),
         vehicles = as.character(vehicles),
         starships = as.character(starships),
         name = as.factor(name))

swInput <- reactive({
  starwars <- starwars.load %>%
    # Slider Filter
    filter(birth_year >= input$birthSelect[1] & birth_year <= input$birthSelect[2])
  # Homeworld Filter
  if (length(input$worldSelect) > 0 ) {
    starwars <- subset(starwars, homeworld %in% input$worldSelect)
  }
  
  return(starwars)
})
# Reactive melted data
mwInput <- reactive({
  swInput() %>%
    melt(id = "name")
})
```

Plot
=====================================

Sidebar {.sidebar}
-------------------------------------

```{r}
selectInput("worldSelect",
               "Homeworld:",
               choices = sort(unique(starwars.load$homeworld)),
               multiple = TRUE,
               selectize = TRUE,
               selected = c("Naboo", "Tatooine"))
   # Birth Selection
   sliderInput("birthSelect",
               "Birth Year:",
               min = min(starwars.load$birth_year, na.rm = T),
               max = max(starwars.load$birth_year, na.rm = T),
               value = c(min(starwars.load$birth_year, na.rm = T), max(starwars.load$birth_year, na.rm = T)),
               step = 1)
```

Row 
-------------------------------------

###

```{r}
renderValueBox({
  sw <- swInput()
  num <- round(mean(sw$mass, na.rm = T), 2)
  
  valueBox("Avg Mass", value = num, icon = "fa-balance-scale", color = "purple")
})
```

###

```{r}
renderValueBox({
  sw <- swInput()
  num <- round(mean(sw$height, na.rm = T), 2)
  
  valueBox("Avg Height", value = num, icon = "fa-sort-numeric-desc", color = "green")
})
```

### Worlds Selected

```{r}
renderGauge({
  rate <- round(as.numeric(length(input$worldSelect)) / length(unique(starwars.load$homeworld)) * 100, 1)
  gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)))
})
```

Row {.tabset .tabset-fade}
-------------------------------------

### Mass

```{r}
renderPlotly({
  dat <- subset(mwInput(), variable == "mass")
  ggplot(data = dat, aes(x = name, y = as.numeric(value), fill = name)) + geom_bar(stat = "identity")
})
```

### Height

```{r}
renderPlotly({
  dat <- subset(mwInput(),  variable == "height")
  ggplot(data = dat, aes(x = name, y = as.numeric(value), fill = name)) + geom_bar(stat = "identity")
})
```

Table
=====================================

Row 
-------------------------------------

### Table 

```{r}
DT::renderDataTable({
  subset(swInput(), select = c(name, height, mass, birth_year, homeworld, species))
})
```

Row 
-------------------------------------

```{r}
library(shiny)

ui <- fluidPage(
  
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```